In [1]:
import pandas as pd

In [2]:
FILE_PATH = r"C:\Users\KDP15\Downloads\kill_match_stats_final_1.csv"

In [3]:
df=pd.read_csv(FILE_PATH)

In [7]:
gun_list = df['killed_by'].unique().tolist()

In [9]:
len(gun_list)

57

In [12]:
df.head(8)

,killed_by,killer_name,killer_placement,killer_position_x,killer_position_y,map,match_id,time,victim_name,victim_placement,victim_position_x,victim_position_y
0,SCAR-L,854545656,1.0,366716.6,302736.6,MIRAMAR,2U4GBNA0YmmZtkItUaRt5bERD2XnqEiYq0Lv_ysjwIZsUH...,1059,SmileyRiley,32.0,366591.3,302851.8
1,AKM,chane_e,57.0,436041.6,276913.3,MIRAMAR,2U4GBNA0YmmZtkItUaRt5bERD2XnqEiYq0Lv_ysjwIZsUH...,109,bonesaw53,85.0,434867.2,276258.3
2,Hit by Car,LY0629,42.0,265942.7,404094.2,MIRAMAR,2U4GBNA0YmmZtkItUaRt5bERD2XnqEiYq0Lv_ysjwIZsUH...,624,Robi256,44.0,265409.5,403900.4
3,SKS,Supramida,6.0,339174.6,258929.0,MIRAMAR,2U4GBNA0YmmZtkItUaRt5bERD2XnqEiYq0Lv_ysjwIZsUH...,1450,Senorbotches,14.0,331995.5,253868.1
4,M416,scopionzy,3.0,289848.4,290939.0,MIRAMAR,2U4GBNA0YmmZtkItUaRt5bERD2XnqEiYq0Lv_ysjwIZsUH...,1296,lukesteeler,24.0,290196.1,291358.5
5,M416,CkYong,28.0,442346.3,241735.7,MIRAMAR,2U4GBNA0YmmZtkItUaRt5bERD2XnqEiYq0Lv_ysjwIZsUH...,949,Hasamalickem,34.0,442369.5,240785.0
6,Punch,kinjazzy,20.0,162442.7,746283.9,MIRAMAR,2U4GBNA0YmmZtkItUaRt5bERD2XnqEiYq0Lv_ysjwIZsUH...,130,BUBPHACHART13,80.0,162481.9,746353.8
7,S1897,19981019Z,46.0,474134.9,264956.8,MIRAMAR,2U4GBNA0YmmZtkItUaRt5bERD2XnqEiYq0Lv_ysjwIZsUH...,224,2KaySeR2,65.0,474685.3,265085.1

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13440889 entries, 0 to 13440888
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   killed_by          object
 1   killer_name        object
 2   killer_placement   float64
 3   killer_position_x  float64
 4   killer_position_y  float64
 5   map                object
 6   match_id           object
 7   time               int64
 8   victim_name        object
 9   victim_placement   float64
 10  victim_position_x  float64
 11  victim_position_y  float64
dtypes: float64(6), int64(1), object(5)
memory usage: 1.2+ GB